### PR TITLE
Packaging for release 7.1.0

### PR DESCRIPTION
**Pull request by DrewMartin**
To include https://github.com/Shopify/shopify_api/pull/611

### CODE REVIEW

**Comment by jtgrenz** [comment]
theres a few other PRs that were pending final review, so might be better to wait for those. I had #600 and #605 that just got a final look and need to be rebased. I'll merge those now this morning if you wanna roll them all up together.

**Comment by DrewMartin** [comment]
Sure thing. Should they be included in the release notes as well?

**Comment by jtgrenz** [comment]
for 605, maybe just add

>`ShopifyAPI::Base.api_version` now defaults to `ShopifyAPI::ApiVersion::NullVersion` instead of `nil`. Making requests without first setting an ApiVersion raises `ApiVersionNotSetError` instead of `NoMethodError: undefined method 'construct_api_path' for nil:NilClass'`

or something. Just waiting on CI for that one

**Comment by DrewMartin** [comment]
Updated to include note for #605. Talked to @jtgrenz and #600 will go out separately, probably with a major version bump

**Pull request merged**
