### PR TITLE
Add tax service files

### PR DESCRIPTION
**Pull request by andrewpaliga**
/cc @dtKinger

### CODE REVIEW

**Comment by andrewpaliga** [comment]
@aprofeit @ch33sybr3ad any objections to merging this?

@dominiquesr anyone else I should ping for review?

**Comment by ch33sybr3ad** [comment]
Wouldn't you also need an `activate` method for the tax_services?

**Comment by andrewpaliga** [comment]
@ch33sybr3ad I don't think that's needed for json requests.

**Comment by aprofeit** [comment]
> Wouldn't you also need an activate method for the tax_services?

@Mavvie would probably have a definitive answer, but the controller doesn't respond to `json` for that action, so I would assume it was never intended to be used via API.

**Comment by ch33sybr3ad** [comment]
ahh, true. I just did a quick look at the controller. other than that LGTM :+1:

**Comment by Mavvie** [comment]
@aprofeit is correct for now, but I'm working on some changes that add API access to the `activate` endpoint.

I would add it to this PR, even if you have to wait for me to merge mine.

**Comment by aprofeit** [comment]
@Mavvie I don't think we should add code to the gem that we know won't work yet.

Also, why do you need a custom action for `activate`? Why not just use `update` with `active: false` in the params?

**Comment by andrewpaliga** [comment]
Okay will merge this for now, once it's available in Shopify we can change.

**Comment by Mavvie** [comment]
Yea I meant we'd hold off on the PR until it's merged.

But merging now and changing it later works too :+1: 

> Also, why do you need a custom action for activate? Why not just use update with active: true|false in the params?

We want `activate` to be separate from other things you can update. This way people can't accidentally activate/deactivate a tax service when they try to update, say, the name.

**Pull request merged**
