### PR TITLE
Bump to v4.0.1

### PR DESCRIPTION
**Pull request by nickhoffman**
bump

/review @csaunders, @ilikeorangutans

### CODE REVIEW

**Comment by csaunders** [comment]
coolbeans

On Mon, May 4, 2015 at 2:41 PM, Nick Hoffman <notifications@github.com>
wrote:

> nickhoffman wants to merge 3 commits into master from v4_0_1:
>
> [image: bump]
> <https://camo.githubusercontent.com/d3f7f9f67266159f77cf4432734ebab0d486bd29/687474703a2f2f6d656469612e67697068792e636f6d2f6d656469612f384c627343516468336375512f67697068792e676966>
>
> /review @csaunders <https://github.com/csaunders>, @ilikeorangutans
> <https://github.com/ilikeorangutans>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Shopify/shopify_api/pull/186
> Commit Summary
>
>    - Bump to v4.0.1 .
>    - In CHANGELOG, stop saying that v3.2.6 is unreleased.
>    - Add v4.0.1 to CHANGELOG.
>
> File Changes
>
>    - *M* CHANGELOG
>    <https://github.com/Shopify/shopify_api/pull/186/files#diff-0> (6)
>    - *M* lib/shopify_api/version.rb
>    <https://github.com/Shopify/shopify_api/pull/186/files#diff-1> (2)
>
> Patch Links:
>
>    - https://github.com/Shopify/shopify_api/pull/186.patch
>    - https://github.com/Shopify/shopify_api/pull/186.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shopify/shopify_api/pull/186>.
>



-- 
Chris Saunders // Developer @ Shopify

**Comment by ilikeorangutans** [comment]
Looks good to me when CI is green :) also, :+1: for manateeeee

**Comment by nickhoffman** [comment]
Hm, why would CI have failed here? It says it couldn't find v4.0.0, which is weird.

**Comment by nickhoffman** [comment]
n/m. :green_apple:

**Pull request merged**
