### PR TITLE
Singularize ResourceFeedback collection_name

### PR DESCRIPTION
**Pull request by chrisbutcher**
Singularize ResourceFeedback `collection_name`, to coincide with API path change to rename endpoint to `/admin/resource_feedback`

### CODE REVIEW

**Comment by jamiemtdwyer** [comment]
If this is a breaking change, we should bump the version and re-deploy

**Comment by maartenvg** [comment]
Considering our chat yesterday, I assume this is no longer necessary?

**Comment by chrisbutcher** [comment]
@maartenvg I think this change still applies. We'll keep index returning an array of (by default 1 feedback record). This change is simply to make the name less awkward to outside parties, since the word `feedback` is already plural.

**Comment by chrisbutcher** [comment]
@jamiemtdwyer Yep, for sure

**Comment by maartenvg** [comment]
> since the word feedback is already plural.

:+1:

**Pull request merged**
