### PR TITLE
add checkout settings model

### PR DESCRIPTION
**Pull request by zacharyreynochiasson**
Adds checkout settings api model

### CODE REVIEW

**Comment by jamiemtdwyer** [comment]
@maartenvg @Matt888 mind having a 👀 guys?

**Comment by Matt888** [comment]
What are checkout settings?

**Comment by maartenvg** [comment]
I believe this is a bit premature. Let's decide on whether we're going to expose this first.

**Comment by zacharyreynochiasson** [comment]
No immediate need.

**Pull request closed without merging**
