### PR TITLE
Adding GiftCardAdjustment

### PR DESCRIPTION
**Pull request by iloveitaly**
This was missing from the library.

### CODE REVIEW

**Comment by jamiemtdwyer** [comment]
I think this class should be defined in its own file to be consistent with the rest of the resources.

**Comment by jamiemtdwyer** [comment]
Also needs tests as well – I can help if needed.

**Comment by iloveitaly** [comment]
@jamiemtdwyer unfortunately I'm not actively working on this project anymore—I won't have the time to make these changes :(

In case anyone else is interested, I've bundled this object into this library:

https://github.com/iloveitaly/shopify_api_extensions

**Comment by nwtn** [comment]
Closing because these changes were extracted into a separate gem

**Pull request closed without merging**
