### PR TITLE
Fix rubocop conflicts

### PR DESCRIPTION
**Pull request by mkevinosullivan**
### rubocop updates for
- Layout/LineLength
- Style/MethodCallWithArgsParentheses (some updates missed/different to those autocorrected in #791)

### CODE REVIEW

**Comment by andyw8** [comment]
@mkevinosullivan Are these all auto-corrections?

**Comment by mkevinosullivan** [comment]
No, went through them manually, running `rake test` after almost every file change!

**Comment by paulomarg** [comment]
Seems like we're still failing for some test files.

**Comment by mkevinosullivan** [comment]
Weird, they all passed on my local machine .. I've just pushed another commit.

**Comment by paulomarg** [comment]
> Weird, they all passed on my local machine .. I've just pushed another commit.

That actually happened to me as well when I turned rubocop on. It seems that some of the rules behave differently for different Ruby versions.

**Comment by andyw8** [comment]
One difficulty with this repo is that we don't commit Gemfile.lock, so there is no guarantee that you'll be running the same version of RuboCop as someone else, or as CI.

**Comment by andyw8** [comment]
> One difficulty with this repo is that we don't commit Gemfile.lock, so there is no guarantee that you'll be running the same version of RuboCop as someone else, or as CI.

^ now fixed in https://github.com/Shopify/shopify_api/pull/788

**Review by paulomarg — APPROVED** [review]
Skipped checking the tests, but the other files LGTM!

**Review by andyw8 — APPROVED** [review]

**Pull request merged**
