### PR TITLE
Packaging for release 6.0.0

### PR DESCRIPTION
**Pull request by clayton-shopify**
Changeset: https://github.com/Shopify/shopify_api/compare/v5.2.4...3de3a6a9fd01d062e0bb6ae662e98e9e9f0e41a0

### CODE REVIEW

**Comment by nwtn** [comment]
At quick glance #479 looks like a breaking change. Should this be a major version instead?

**Comment by clayton-shopify** [comment]
I brought that up with @jamiemtdwyer back when I opened #479 but he didn't think it was worth a major version bump. Although unlikely, there are a couple scenarios where things could potentially break:

* tests that use a simulated version of Shopify
* apps that interface with a proxy server instead of connecting to Shopify directly

I'm not against changing the version number to 6.0.0 to address the small chance of breakage.

**Comment by nwtn** [comment]
OK. Given that this is open/public and our partners could be using it differently than we are internally, I’d prefer to go with 6.0.0.

**Comment by clayton-shopify** [comment]
OK, I've changed it to 6.0.0.

**Comment by jamiemtdwyer** [comment]
I still think that a major version bump is overkill. Consider that partner developers don't have access to a local instance of Shopify, so I'm not sure how they could access the Shopify API on any other port.

I'll defer to @nwtn though.

**Comment by nwtn** [comment]
> I still think that a major version bump is overkill. Consider that partner developers don't have access to a local instance of Shopify, so I'm not sure how they could access the Shopify API on any other port.

It’s the proxying thing that I’m more concerned about. I agree it’s a pretty small chance that it’ll break, but I don’t think there’s any real harm in doing it as a major release, and it at least signals that folks should exercise some caution when adopting.

**Pull request merged**
