### PR TITLE
Update DeliveryConfirmation and Conversation Ping resources for Feedback API

### PR DESCRIPTION
**Pull request by Tieshia**
Updated DeliveryConfirmation resource and Conversation methods to un-nest delivery_confirmation_details hash required for Feedback API endpoint.

### CODE REVIEW

**Comment by Tieshia** [comment]
@Shopify/app-partner-dev-tools-education Greetings! Might it be possible to get a review on this?

**Comment by Tieshia** [comment]
@Shopify/app-partner-dev-tools-education Hi! Can I get a review on this please?

**Comment by nwtn** [comment]
Was this failing with the previous behaviour before this change? Should we add/update any tests to capture the new pattern and make sure we don’t regress?

**Comment by Tieshia** [comment]
@nwtn The tests initially written verified whether or attributes were correctly assigned a successful/unsuccessful delivery event, which doesn't change with this update. This change resolves `delivery_confirmation_details` being implicitly nested under `delivery_confirmation`, and has been successfully tested locally on Ping.

**Comment by Tieshia** [comment]
Thank you, @nwtn!

**Pull request merged**
