### PR TITLE
Fix a typo in inventory_level.rb

### PR DESCRIPTION
**Pull request by RomainMorlevat**

### CODE REVIEW

**Comment by katiedavis** [comment]
Also @RomainMorlevat please make sure to sign the CLA

**Comment by RomainMorlevat** [comment]
> Also @RomainMorlevat please make sure to sign the CLA

Done, but how do I run again the CLA check ?

**Comment by katiedavis** [comment]
> > Also @RomainMorlevat please make sure to sign the CLA
> 
> Done, but how do I run again the CLA check ?

I'm not sure you can. I rerun it for you though. You're good to merge!

**Comment by andyw8** [comment]
Thank you @RomainMorlevat, and sorry for the delay.

**Pull request merged**
